ARG TAG=latest
FROM bitnami/mongodb:${TAG}

# Should be defined by enviroment:
  # MONGODB_REPLICA_SET_MODE=primary
  # MONGODB_ADVERTISED_HOSTNAME=rs0
  # MONGODB_ROOT_USER=admin
  # MONGODB_ROOT_PASSWORD=password
  # MONGODB_REPLICA_SET_KEY=mongodbkey

EXPOSE 27017
